---
# a lot of this cribbed from
# https://github.com/cask/cask/blob/467979414c85bb2ce83f5c6ab9f95721164e9efa/.github/workflows/test.yml
name: test

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        emacs_version: [24.5, 25.3, 26.3, 27.2]
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: set paths
        run: |
          echo "$HOME/local/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$HOME/.local/lib" >> $GITHUB_ENV
      - run: 'make test'
        continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
      # - if: startsWith(matrix.emacs_version, '27')
      #   run: 'make install'
